version: "3.7"

networks:
  proxy:
    external: true

volumes:
  node_modules:

services:
  app:
    restart: always
    command: npm run prd
    networks:
      - proxy
    volumes:
      - node_modules:/app/node_modules
    env_file:
      - deploy.env

  db:
    restart: always

  selenium:
    restart: always
