version: "3.7"

volumes:
  db:
  db_admin:
  portainer:

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
      - 5858:5858
      - 9229:9229
    environment:
      NODE_ENV: development
      PG_HOST: db
      PG_PORT: 5432
      PG_DB_NAME: db
      PG_USER: postgres
      PG_PASS: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      SLACK_WEBHOOK: https://hooks.slack.com/services/...
      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 465
      MAILER_USER: webmaster@domain.com
      MAILER_PASS: P@ssword
      MAILER_FROM: Domain
    depends_on:
      - db
      - redis
      - selenium

  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db_admin:
    image: dpage/pgadmin4:latest
    volumes:
      - db_admin:/var/lib/pgadmin
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    expose:
      - 4444

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    ports:
      - 9000:9000
